/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppAcademyRouteImport } from './routes/_app/academy'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAiChatRouteImport } from './routes/_app/ai-chat'
import { Route as AppCallsRouteImport } from './routes/_app/calls'
import { Route as AppCoachRouteImport } from './routes/_app/coach'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppGamesRouteImport } from './routes/_app/games'
import { Route as AppGrammarRouteImport } from './routes/_app/grammar'
import { Route as AppHindiRouteImport } from './routes/_app/hindi'
import { Route as AppLearnRouteImport } from './routes/_app/learn'
import { Route as AppLessonRouteImport } from './routes/_app/lesson'
import { Route as AppListeningRouteImport } from './routes/_app/listening'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMirrorRouteImport } from './routes/_app/mirror'
import { Route as AppMistakesRouteImport } from './routes/_app/mistakes'
import { Route as AppPathRouteImport } from './routes/_app/path'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppPronunciationRouteImport } from './routes/_app/pronunciation'
import { Route as AppRoleplayRouteImport } from './routes/_app/roleplay'
import { Route as AppRoundTableRouteImport } from './routes/_app/round-table'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSpeakRouteImport } from './routes/_app/speak'
import { Route as AppThinkingRouteImport } from './routes/_app/thinking'
import { Route as AppTranslatorRouteImport } from './routes/_app/translator'
import { Route as AppVocabularyRouteImport } from './routes/_app/vocabulary'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as AppCallCodeRouteImport } from './routes/_app/call.$code'
import { Route as AppGamesIndexRouteImport } from './routes/_app/games.index'
import { Route as AppGamesIdRouteImport } from './routes/_app/games.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppGrammarRoute = AppGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AppRoute,
} as any)
const AppHindiRoute = AppHindiRouteImport.update({
  id: '/hindi',
  path: '/hindi',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonRoute = AppLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => AppRoute,
} as any)
const AppListeningRoute = AppListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMirrorRoute = AppMirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => AppRoute,
} as any)
const AppMistakesRoute = AppMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppRoute,
} as any)
const AppPathRoute = AppPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppPronunciationRoute = AppPronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleplayRoute = AppRoleplayRouteImport.update({
  id: '/roleplay',
  path: '/roleplay',
  getParentRoute: () => AppRoute,
} as any)
const AppRoundTableRoute = AppRoundTableRouteImport.update({
  id: '/round-table',
  path: '/round-table',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakRoute = AppSpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => AppRoute,
} as any)
const AppThinkingRoute = AppThinkingRouteImport.update({
  id: '/thinking',
  path: '/thinking',
  getParentRoute: () => AppRoute,
} as any)
const AppTranslatorRoute = AppTranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => AppRoute,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallCodeRoute = AppCallCodeRouteImport.update({
  id: '/call/$code',
  path: '/call/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGamesRoute,
} as any)
const AppGamesIdRoute = AppGamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGamesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/academy': typeof AppAcademyRoute
  '/admin': typeof AppAdminRoute
  '/ai-chat': typeof AppAiChatRoute
  '/calls': typeof AppCallsRoute
  '/coach': typeof AppCoachRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/games': typeof AppGamesRouteWithChildren
  '/grammar': typeof AppGrammarRoute
  '/hindi': typeof AppHindiRoute
  '/learn': typeof AppLearnRoute
  '/lesson': typeof AppLessonRoute
  '/listening': typeof AppListeningRoute
  '/messages': typeof AppMessagesRoute
  '/mirror': typeof AppMirrorRoute
  '/mistakes': typeof AppMistakesRoute
  '/path': typeof AppPathRoute
  '/pricing': typeof AppPricingRoute
  '/progress': typeof AppProgressRoute
  '/pronunciation': typeof AppPronunciationRoute
  '/roleplay': typeof AppRoleplayRoute
  '/round-table': typeof AppRoundTableRoute
  '/settings': typeof AppSettingsRoute
  '/speak': typeof AppSpeakRoute
  '/thinking': typeof AppThinkingRoute
  '/translator': typeof AppTranslatorRoute
  '/vocabulary': typeof AppVocabularyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/join/$slug': typeof JoinSlugRoute
  '/call/$code': typeof AppCallCodeRoute
  '/games/$id': typeof AppGamesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/': typeof AppGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/academy': typeof AppAcademyRoute
  '/admin': typeof AppAdminRoute
  '/ai-chat': typeof AppAiChatRoute
  '/calls': typeof AppCallsRoute
  '/coach': typeof AppCoachRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/grammar': typeof AppGrammarRoute
  '/hindi': typeof AppHindiRoute
  '/learn': typeof AppLearnRoute
  '/lesson': typeof AppLessonRoute
  '/listening': typeof AppListeningRoute
  '/messages': typeof AppMessagesRoute
  '/mirror': typeof AppMirrorRoute
  '/mistakes': typeof AppMistakesRoute
  '/path': typeof AppPathRoute
  '/pricing': typeof AppPricingRoute
  '/progress': typeof AppProgressRoute
  '/pronunciation': typeof AppPronunciationRoute
  '/roleplay': typeof AppRoleplayRoute
  '/round-table': typeof AppRoundTableRoute
  '/settings': typeof AppSettingsRoute
  '/speak': typeof AppSpeakRoute
  '/thinking': typeof AppThinkingRoute
  '/translator': typeof AppTranslatorRoute
  '/vocabulary': typeof AppVocabularyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/join/$slug': typeof JoinSlugRoute
  '/call/$code': typeof AppCallCodeRoute
  '/games/$id': typeof AppGamesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games': typeof AppGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/academy': typeof AppAcademyRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai-chat': typeof AppAiChatRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/games': typeof AppGamesRouteWithChildren
  '/_app/grammar': typeof AppGrammarRoute
  '/_app/hindi': typeof AppHindiRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/lesson': typeof AppLessonRoute
  '/_app/listening': typeof AppListeningRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/mirror': typeof AppMirrorRoute
  '/_app/mistakes': typeof AppMistakesRoute
  '/_app/path': typeof AppPathRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/pronunciation': typeof AppPronunciationRoute
  '/_app/roleplay': typeof AppRoleplayRoute
  '/_app/round-table': typeof AppRoundTableRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/speak': typeof AppSpeakRoute
  '/_app/thinking': typeof AppThinkingRoute
  '/_app/translator': typeof AppTranslatorRoute
  '/_app/vocabulary': typeof AppVocabularyRoute
  '/api/rtc': typeof ApiRtcRoute
  '/join/$slug': typeof JoinSlugRoute
  '/_app/call/$code': typeof AppCallCodeRoute
  '/_app/games/$id': typeof AppGamesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/games/': typeof AppGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/login'
    | '/onboarding'
    | '/academy'
    | '/admin'
    | '/ai-chat'
    | '/calls'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/games'
    | '/grammar'
    | '/hindi'
    | '/learn'
    | '/lesson'
    | '/listening'
    | '/messages'
    | '/mirror'
    | '/mistakes'
    | '/path'
    | '/pricing'
    | '/progress'
    | '/pronunciation'
    | '/roleplay'
    | '/round-table'
    | '/settings'
    | '/speak'
    | '/thinking'
    | '/translator'
    | '/vocabulary'
    | '/api/rtc'
    | '/join/$slug'
    | '/call/$code'
    | '/games/$id'
    | '/api/auth/$'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/login'
    | '/onboarding'
    | '/academy'
    | '/admin'
    | '/ai-chat'
    | '/calls'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/grammar'
    | '/hindi'
    | '/learn'
    | '/lesson'
    | '/listening'
    | '/messages'
    | '/mirror'
    | '/mistakes'
    | '/path'
    | '/pricing'
    | '/progress'
    | '/pronunciation'
    | '/roleplay'
    | '/round-table'
    | '/settings'
    | '/speak'
    | '/thinking'
    | '/translator'
    | '/vocabulary'
    | '/api/rtc'
    | '/join/$slug'
    | '/call/$code'
    | '/games/$id'
    | '/api/auth/$'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/assessment'
    | '/login'
    | '/onboarding'
    | '/_app/academy'
    | '/_app/admin'
    | '/_app/ai-chat'
    | '/_app/calls'
    | '/_app/coach'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/games'
    | '/_app/grammar'
    | '/_app/hindi'
    | '/_app/learn'
    | '/_app/lesson'
    | '/_app/listening'
    | '/_app/messages'
    | '/_app/mirror'
    | '/_app/mistakes'
    | '/_app/path'
    | '/_app/pricing'
    | '/_app/progress'
    | '/_app/pronunciation'
    | '/_app/roleplay'
    | '/_app/round-table'
    | '/_app/settings'
    | '/_app/speak'
    | '/_app/thinking'
    | '/_app/translator'
    | '/_app/vocabulary'
    | '/api/rtc'
    | '/join/$slug'
    | '/_app/call/$code'
    | '/_app/games/$id'
    | '/api/auth/$'
    | '/_app/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiRtcRoute: typeof ApiRtcRoute
  JoinSlugRoute: typeof JoinSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/academy': {
      id: '/_app/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-chat': {
      id: '/_app/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games': {
      id: '/_app/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grammar': {
      id: '/_app/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AppGrammarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hindi': {
      id: '/_app/hindi'
      path: '/hindi'
      fullPath: '/hindi'
      preLoaderRoute: typeof AppHindiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson': {
      id: '/_app/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof AppLessonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listening': {
      id: '/_app/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AppListeningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mirror': {
      id: '/_app/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof AppMirrorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mistakes': {
      id: '/_app/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AppMistakesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/path': {
      id: '/_app/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof AppPathRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pronunciation': {
      id: '/_app/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof AppPronunciationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roleplay': {
      id: '/_app/roleplay'
      path: '/roleplay'
      fullPath: '/roleplay'
      preLoaderRoute: typeof AppRoleplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/round-table': {
      id: '/_app/round-table'
      path: '/round-table'
      fullPath: '/round-table'
      preLoaderRoute: typeof AppRoundTableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speak': {
      id: '/_app/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof AppSpeakRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thinking': {
      id: '/_app/thinking'
      path: '/thinking'
      fullPath: '/thinking'
      preLoaderRoute: typeof AppThinkingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/translator': {
      id: '/_app/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof AppTranslatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocabulary': {
      id: '/_app/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/call/$code': {
      id: '/_app/call/$code'
      path: '/call/$code'
      fullPath: '/call/$code'
      preLoaderRoute: typeof AppCallCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/_app/games/$id': {
      id: '/_app/games/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AppGamesIdRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppGamesRouteChildren {
  AppGamesIdRoute: typeof AppGamesIdRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
}

const AppGamesRouteChildren: AppGamesRouteChildren = {
  AppGamesIdRoute: AppGamesIdRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
}

const AppGamesRouteWithChildren = AppGamesRoute._addFileChildren(
  AppGamesRouteChildren,
)

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAiChatRoute: typeof AppAiChatRoute
  AppCallsRoute: typeof AppCallsRoute
  AppCoachRoute: typeof AppCoachRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGamesRoute: typeof AppGamesRouteWithChildren
  AppGrammarRoute: typeof AppGrammarRoute
  AppHindiRoute: typeof AppHindiRoute
  AppLearnRoute: typeof AppLearnRoute
  AppLessonRoute: typeof AppLessonRoute
  AppListeningRoute: typeof AppListeningRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMirrorRoute: typeof AppMirrorRoute
  AppMistakesRoute: typeof AppMistakesRoute
  AppPathRoute: typeof AppPathRoute
  AppPricingRoute: typeof AppPricingRoute
  AppProgressRoute: typeof AppProgressRoute
  AppPronunciationRoute: typeof AppPronunciationRoute
  AppRoleplayRoute: typeof AppRoleplayRoute
  AppRoundTableRoute: typeof AppRoundTableRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpeakRoute: typeof AppSpeakRoute
  AppThinkingRoute: typeof AppThinkingRoute
  AppTranslatorRoute: typeof AppTranslatorRoute
  AppVocabularyRoute: typeof AppVocabularyRoute
  AppCallCodeRoute: typeof AppCallCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRoute,
  AppAdminRoute: AppAdminRoute,
  AppAiChatRoute: AppAiChatRoute,
  AppCallsRoute: AppCallsRoute,
  AppCoachRoute: AppCoachRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGamesRoute: AppGamesRouteWithChildren,
  AppGrammarRoute: AppGrammarRoute,
  AppHindiRoute: AppHindiRoute,
  AppLearnRoute: AppLearnRoute,
  AppLessonRoute: AppLessonRoute,
  AppListeningRoute: AppListeningRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMirrorRoute: AppMirrorRoute,
  AppMistakesRoute: AppMistakesRoute,
  AppPathRoute: AppPathRoute,
  AppPricingRoute: AppPricingRoute,
  AppProgressRoute: AppProgressRoute,
  AppPronunciationRoute: AppPronunciationRoute,
  AppRoleplayRoute: AppRoleplayRoute,
  AppRoundTableRoute: AppRoundTableRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpeakRoute: AppSpeakRoute,
  AppThinkingRoute: AppThinkingRoute,
  AppTranslatorRoute: AppTranslatorRoute,
  AppVocabularyRoute: AppVocabularyRoute,
  AppCallCodeRoute: AppCallCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiRtcRoute: ApiRtcRoute,
  JoinSlugRoute: JoinSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
